import argparse
import json
from typing import Any

from agent import CybersecurityRiskAgent


def create_argument_parser() -> argparse.ArgumentParser:
    """
    Create command-line argument parser for the application.

    Returns:
        Configured ArgumentParser object.
    """
    parser = argparse.ArgumentParser(
        description="Cybersecurity Network Risk Analyzer Agent"
    )

    parser.add_argument(
        "--file",
        required=True,
        help="Path to an existing Nmap XML scan result file.",
    )

    parser.add_argument(
        "--no-save",
        action="store_true",
        help="Display the result without saving a JSON report file.",
    )

    return parser


def print_summary(result: dict[str, Any]) -> None:
    """
    Print a readable summary of the cybersecurity risk analysis.

    Args:
        result: Final report generated by the agent.
    """
    print("\nCybersecurity Network Risk Analyzer Agent")
    print("-" * 50)
    print(f"Target: {result['target']}")
    print(f"Open ports found: {result['open_port_count']}")
    print(f"Overall risk level: {result['overall_risk']['overall_level']}")
    print(f"Overall risk score: {result['overall_risk']['overall_score']}")
    print("\nFindings:")

    if not result["findings"]:
        print("No open services were detected.")
    else:
        for finding in result["findings"]:
            print(
                f"- Port {finding['port']} / {finding['service']} "
                f"({finding['risk']['risk_level']} risk)"
            )
            print(f"  Reason: {finding['risk']['reason']}")
            print(f"  Recommendation: {finding['risk']['recommendation']}")

    print("\nConclusion:")
    print(result["overall_risk"]["conclusion"])

    if "saved_report" in result:
        print(f"\nSaved report: {result['saved_report']}")


def main() -> None:
    """
    Main command-line entry point for the system.
    """
    parser = create_argument_parser()
    args = parser.parse_args()

    agent = CybersecurityRiskAgent(save_reports=not args.no_save)

    try:
        result = agent.analyze_scan_file(args.file)
    except Exception as error:
        print(f"Error: {error}")
        raise SystemExit(1)

    print_summary(result)

    print("\nFull JSON result:")
    print(json.dumps(result, indent=4))


if __name__ == "__main__":
    main()