from typing import Any


RISK_RULES: dict[int, dict[str, Any]] = {
    21: {
        "service": "FTP",
        "risk_level": "High",
        "score": 7,
        "reason": "FTP may transmit credentials insecurely if it is not protected.",
        "recommendation": "Use SFTP or FTPS and restrict access to trusted users.",
    },
    22: {
        "service": "SSH",
        "risk_level": "Medium",
        "score": 5,
        "reason": "SSH is commonly targeted by brute-force login attempts.",
        "recommendation": "Use key-based authentication, disable root login, and limit access.",
    },
    23: {
        "service": "Telnet",
        "risk_level": "Critical",
        "score": 9,
        "reason": "Telnet uses unencrypted communication and can expose credentials.",
        "recommendation": "Disable Telnet and use SSH instead.",
    },
    25: {
        "service": "SMTP",
        "risk_level": "Medium",
        "score": 5,
        "reason": "SMTP can be abused if it is misconfigured as an open relay.",
        "recommendation": "Check mail server configuration and prevent open relay behavior.",
    },
    53: {
        "service": "DNS",
        "risk_level": "Medium",
        "score": 5,
        "reason": "DNS services may expose internal information if misconfigured.",
        "recommendation": "Restrict zone transfers and review DNS configuration.",
    },
    80: {
        "service": "HTTP",
        "risk_level": "Medium",
        "score": 5,
        "reason": "HTTP traffic is unencrypted and may expose sensitive information.",
        "recommendation": "Use HTTPS and keep the web server updated.",
    },
    443: {
        "service": "HTTPS",
        "risk_level": "Low",
        "score": 2,
        "reason": "HTTPS is generally safer when configured correctly.",
        "recommendation": "Keep TLS configuration and certificates up to date.",
    },
    3306: {
        "service": "MySQL",
        "risk_level": "High",
        "score": 7,
        "reason": "Database ports should not usually be exposed publicly.",
        "recommendation": "Restrict database access to trusted internal systems only.",
    },
    3389: {
        "service": "RDP",
        "risk_level": "High",
        "score": 7,
        "reason": "Remote desktop services are commonly targeted by attackers.",
        "recommendation": "Limit RDP access, use VPN, and enable strong authentication.",
    },
    5432: {
        "service": "PostgreSQL",
        "risk_level": "High",
        "score": 7,
        "reason": "Database exposure may allow unauthorized access attempts.",
        "recommendation": "Restrict PostgreSQL access to trusted hosts only.",
    },
}


def analyze_service_risk(port: int, service_name: str = "unknown") -> dict[str, Any]:
    """
    Analyze the risk level of a detected network service.

    The function checks the detected port against a predefined cybersecurity
    rule dictionary. Each rule contains a risk level, numeric score, reason,
    and recommendation.

    Args:
        port: Detected open port number.
        service_name: Detected service name.

    Returns:
        A dictionary containing risk level, score, reason, and recommendation.
    """
    rule = RISK_RULES.get(port)

    if rule:
        return {
            "risk_level": rule["risk_level"],
            "score": rule["score"],
            "reason": rule["reason"],
            "recommendation": rule["recommendation"],
        }

    return {
        "risk_level": "Low",
        "score": 2,
        "reason": f"The service '{service_name}' is open, but no specific high-risk rule was found.",
        "recommendation": "Verify whether this service is required and restrict access if possible.",
    }


def calculate_overall_risk(findings: list[dict[str, Any]]) -> dict[str, Any]:
    """
    Calculate the overall risk level from analyzed findings.

    The current strategy uses the highest detected service risk score as the
    overall risk score. This makes high-risk exposed services visible even if
    other detected services are lower risk.

    Args:
        findings: List of findings generated by the agent.

    Returns:
        A dictionary containing overall score, level, and conclusion.
    """
    if not findings:
        return {
            "overall_score": 0,
            "overall_level": "Low",
            "conclusion": "No open services were detected in the scan result.",
        }

    highest_score = max(item["risk"]["score"] for item in findings)

    if highest_score >= 9:
        overall_level = "Critical"
    elif highest_score >= 7:
        overall_level = "High"
    elif highest_score >= 5:
        overall_level = "Medium"
    else:
        overall_level = "Low"

    if overall_level in {"Critical", "High"}:
        conclusion = (
            "The host has services that require attention. "
            "High-risk or critical services should be reviewed first."
        )
    elif overall_level == "Medium":
        conclusion = (
            "The host has exposed services with moderate risk. "
            "Configuration and access control should be reviewed."
        )
    else:
        conclusion = (
            "The scan result shows low overall risk, but exposed services should still be monitored."
        )

    return {
        "overall_score": highest_score,
        "overall_level": overall_level,
        "conclusion": conclusion,
    }


def get_supported_rules() -> dict[int, dict[str, Any]]:
    """
    Return the current predefined risk rule dictionary.

    This function makes it easier to inspect, test, and later expand the
    rule set without directly modifying other parts of the system.

    Returns:
        The current risk rule dictionary.
    """
    return RISK_RULES